### 채널 등록
POST http://localhost:8080/v1/channels
Content-Type: application/json

{
  "channelName": "test"
}

### 채널에 메시지 추가
POST http://localhost:8080/v1/channels/test/messages-publication
Content-Type: application/json

{
  "createdAt": "2025-01-01T00:00:00",
  "data": {
    "id": 2
  }
}

### 채널 조회
GET http://localhost:8080/v1/channels/test
Content-Type: application/json
